name := "play-hmrc-api"

val scala2_13 = "2.13.12"

ThisBuild / scalaVersion := scala2_13
ThisBuild / majorVersion := 8
ThisBuild / isPublicArtefact := true
ThisBuild / organization := "uk.gov.hmrc"
ThisBuild / scalacOptions += "-Wconf:src=src_managed/.*:s" // silence all warnings on autogenerated files

lazy val library = (project in file("."))
  .disablePlugins(JUnitXmlReportPlugin)
  .aggregate(
    play28,
    play29,
    play30
  )

lazy val play28 = Project("play-hmrc-api-play-28", file("play-28"))
  .settings(
    scalaVersion := scala2_13,
    libraryDependencies ++= LibraryDependencies.play28 ++ LibraryDependencies.test28,
    libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always,
    sharedSources
  )

lazy val play29 = Project("play-hmrc-api-play-29", file("play-29"))
  .settings(
    scalaVersion := scala2_13,
    libraryDependencies ++= LibraryDependencies.play29 ++ LibraryDependencies.test29,
    sharedSources
  )

lazy val play30 = Project("play-hmrc-api-play-30", file("play-30"))
  .settings(
    scalaVersion := scala2_13,
    libraryDependencies ++= LibraryDependencies.play30 ++ LibraryDependencies.test30,
    sharedSources
  )

def sharedSources = Seq(
  Compile / unmanagedSourceDirectories += baseDirectory.value / "../shared/src/main/scala",
  Compile / unmanagedResourceDirectories += baseDirectory.value / "../shared/src/main/resources",
  Test / unmanagedSourceDirectories += baseDirectory.value / "../shared/src/test/scala",
  Test / unmanagedResourceDirectories += baseDirectory.value / "../shared/src/test/resources"
)
